# Generated by Django 5.0.4 on 2024-06-19 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="event",
            name="image_url",
        ),
        migrations.CreateModel(
            name="MediaUploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="corlee/uploads/")),
                ("caption", models.CharField(blank=True, max_length=256, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corlee_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profile_photos",
                to="cortex_yen_app.mediauploads",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="event_photos",
                to="cortex_yen_app.mediauploads",
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="fabric_photos",
                to="cortex_yen_app.mediauploads",
            ),
        ),
    ]
