# Generated by Django 5.0.4 on 2024-06-19 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cortex_yen_app",
            "0002_remove_blog_image_url_remove_event_image_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediauploads",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="mediauploads",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mediauploads",
            name="owner",
        ),
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_photos",
                to="cortex_yen_app.mediauploads",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blog_photos",
                to="cortex_yen_app.mediauploads",
            ),
        ),
    ]
