# Generated by Django 5.0.4 on 2024-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0004_customuser_auth_method_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="request_number",
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
