# Generated by Django 5.0.4 on 2024-07-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0009_alter_fabric_available_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="aux_photo1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aux_photo1",
                to="cortex_yen_app.mediauploads",
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="aux_photo2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aux_photo2",
                to="cortex_yen_app.mediauploads",
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="aux_photo3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aux_photo3",
                to="cortex_yen_app.mediauploads",
            ),
        ),
    ]
