# Generated by Django 5.0.4 on 2024-07-25 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0010_fabric_aux_photo1_fabric_aux_photo2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="sample_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
