# Generated by Django 5.0.4 on 2024-07-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cortex_yen_app",
            "0011_contactrequest_email_contactrequest_sample_requested_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="request_number",
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="related_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cortex_yen_app.order",
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("product", "Product Inquiry"),
                    ("product_request", "Product Request"),
                ],
                default="general",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="related_fabric",
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="related_fabric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cortex_yen_app.fabric",
            ),
        ),
    ]
