# Generated by Django 5.0.4 on 2024-07-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0014_alter_contactrequest_request_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
