# Generated by Django 5.0.4 on 2024-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0016_rename_tags_blog_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="category",
            new_name="category_temp",
        ),
    ]
