# Generated by Django 5.0.4 on 2024-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0019_alter_blog_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=50)),
                ("county", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=255, null=True)),
                ("line", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
