# Generated by Django 5.0.4 on 2024-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0020_contactdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdetails",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=24.0708, max_digits=9),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=120.5409, max_digits=9),
        ),
    ]
