# Generated by Django 5.0.4 on 2024-08-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0021_contactdetails_latitude_contactdetails_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediauploads",
            name="file",
            field=models.FileField(max_length=255, upload_to="corlee/uploads/"),
        ),
    ]
