# Generated by Django 5.0.4 on 2024-08-02 10:03

import cortex_yen_app.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cortex_yen_app",
            "0026_remove_fabric_aux_photo1_remove_fabric_aux_photo2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabric",
            name="item_code",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_item_code",
                        message="Item code must contain only letters and numbers.",
                        regex="^[a-zA-Z0-9]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fabriccolorimage",
            name="color",
            field=models.CharField(
                max_length=50, validators=[cortex_yen_app.validators.validate_colors]
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cortex_yen_app.mediauploads",
            ),
        ),
    ]
