# Generated by Django 5.0.4 on 2024-08-12 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cortex_yen_app",
            "0027_alter_fabric_item_code_alter_fabriccolorimage_color_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FabricColorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="fabriccolorimage",
            name="color_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colors",
                to="cortex_yen_app.fabriccolorcategory",
            ),
        ),
    ]
