# Generated by Django 5.0.4 on 2024-08-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    def copy_category_to_display_name(apps, schema_editor):
        FabricColorCategory = apps.get_model("cortex_yen_app", "FabricColorCategory")
        for category in FabricColorCategory.objects.all():
            # Use 'category.category' to access the old field values
            # Since the field 'category' no longer exists, this step assumes you still have data in some temporary form
            # If not, you'll need to fetch from backup or a different source
            category.display_name = category.category
            category.save()

    dependencies = [
        ("cortex_yen_app", "0029_contactrequest_current_status_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_category_to_display_name),
    ]
