# Generated by Django 5.0.4 on 2024-08-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0030_auto_20240812_1024"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fabriccolorcategory",
            old_name="category",
            new_name="display_name",
        ),
    ]
