# Generated by Django 5.0.4 on 2024-08-12 05:49

import cortex_yen_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0031_rename_category_fabriccolorcategory_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabriccolorcategory",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[cortex_yen_app.validators.validate_colors],
            ),
        ),
    ]
