# Generated by Django 5.0.4 on 2024-09-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0032_fabriccolorcategory_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="url",
            field=models.URLField(default="https://calendly.com/"),
            preserve_default=False,
        ),
    ]
