# Generated by Django 5.0.4 on 2025-03-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0033_event_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabriccolorimage",
            name="model_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="model_image",
                to="cortex_yen_app.mediauploads",
            ),
        ),
    ]
