# Generated by Django 5.0.4 on 2025-03-19 13:49

from django.db import migrations

def remove_color_if_exists(apps, schema_editor):
    # Check if the column exists before trying to remove it
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='cortex_yen_app_fabriccolorimage' 
                AND column_name='color';
            """)
            if cursor.fetchone():
                schema_editor.execute('ALTER TABLE cortex_yen_app_fabriccolorimage DROP COLUMN color;')

class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0033_event_url'),
    ]

    operations = [
        migrations.RunPython(remove_color_if_exists, reverse_code=migrations.RunPython.noop),
    ]
