# Generated by Django 5.0.4 on 2025-03-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0033_event_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabriccolorimage',
            name='color',
        ),
    ]
