# Generated by Django 5.0.4 on 2025-03-19 14:05

import django.db.models.deletion
from django.db import migrations, models


def add_model_image_if_not_exists(apps, schema_editor):
    # Check if the column exists before trying to add it
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='cortex_yen_app_fabriccolorimage' 
                AND column_name='model_image_id';
            """)
            if not cursor.fetchone():
                schema_editor.execute('ALTER TABLE cortex_yen_app_fabriccolorimage ADD COLUMN model_image_id bigint NULL;')
                schema_editor.execute('ALTER TABLE cortex_yen_app_fabriccolorimage ADD CONSTRAINT cortex_yen_app_fabriccolorimage_model_image_id_fkey FOREIGN KEY (model_image_id) REFERENCES cortex_yen_app_mediauploads(id) ON DELETE NO ACTION;')


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0034_remove_fabriccolorimage_color'),
    ]

    operations = [
        migrations.RunPython(add_model_image_if_not_exists, reverse_code=migrations.RunPython.noop),
    ]
