# Generated by Django 5.0.4 on 2025-03-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cortex_yen_app", "0034_fabriccolorimage_model_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabriccolorimage",
            name="color",
        ),
    ]
