# Generated by Django 5.0.4 on 2025-04-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0035_clean_migration_fix'),
    ]

    operations = [
        # First check if the column exists before trying to remove it
        migrations.RunSQL(
            sql="ALTER TABLE cortex_yen_app_fabriccolorimage DROP COLUMN IF EXISTS color;",
            reverse_sql="ALTER TABLE cortex_yen_app_fabriccolorimage ADD COLUMN color VARCHAR(100);",
        ),
        # Check if name column exists before adding it
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_contactrequest' 
                                 AND column_name = 'name') THEN
                        ALTER TABLE cortex_yen_app_contactrequest ADD COLUMN name VARCHAR(255);
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE cortex_yen_app_contactrequest DROP COLUMN IF EXISTS name;",
        ),
        # Check if phone column exists before adding it
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_contactrequest' 
                                 AND column_name = 'phone') THEN
                        ALTER TABLE cortex_yen_app_contactrequest ADD COLUMN phone VARCHAR(20);
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE cortex_yen_app_contactrequest DROP COLUMN IF EXISTS phone;",
        ),
        # Check if model_image_id column exists before adding it
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_fabriccolorimage' 
                                 AND column_name = 'model_image_id') THEN
                        ALTER TABLE cortex_yen_app_fabriccolorimage ADD COLUMN model_image_id INTEGER REFERENCES cortex_yen_app_mediauploads(id);
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE cortex_yen_app_fabriccolorimage DROP COLUMN IF EXISTS model_image_id;",
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='primary_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_images', to='cortex_yen_app.mediauploads'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_set', to='cortex_yen_app.fabric'),
        ),
    ]
