# Generated by Django 5.0.4 on 2025-04-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0036_remove_fabriccolorimage_color_contactrequest_name_and_more'),
    ]

    operations = [
        # Skip removing the color field since it doesn't exist and was already removed in migration 0036
        # migrations.RemoveField(
        #     model_name='fabriccolorimage',
        #     name='color',
        # ),
        
        # Use RunSQL to conditionally add name field only if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                  WHERE table_name = 'cortex_yen_app_contactrequest' 
                                  AND column_name = 'name') THEN
                        ALTER TABLE cortex_yen_app_contactrequest ADD COLUMN name VARCHAR(255);
                    END IF;
                END $$;
            """,
            reverse_sql="-- No reverse operation needed",
        ),
        
        # Use RunSQL to conditionally add phone field only if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                  WHERE table_name = 'cortex_yen_app_contactrequest' 
                                  AND column_name = 'phone') THEN
                        ALTER TABLE cortex_yen_app_contactrequest ADD COLUMN phone VARCHAR(20);
                    END IF;
                END $$;
            """,
            reverse_sql="-- No reverse operation needed",
        ),
        
        # Use RunSQL to conditionally add mandarin fields to Fabric if they don't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    -- Check and add mandarin fields to Fabric if they don't exist
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_fabric' 
                                 AND column_name = 'composition_mandarin') THEN
                        ALTER TABLE cortex_yen_app_fabric ADD COLUMN composition_mandarin VARCHAR(255);
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_fabric' 
                                 AND column_name = 'description_mandarin') THEN
                        ALTER TABLE cortex_yen_app_fabric ADD COLUMN description_mandarin VARCHAR(100);
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_fabric' 
                                 AND column_name = 'finish_mandarin') THEN
                        ALTER TABLE cortex_yen_app_fabric ADD COLUMN finish_mandarin VARCHAR(100);
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_fabric' 
                                 AND column_name = 'title_mandarin') THEN
                        ALTER TABLE cortex_yen_app_fabric ADD COLUMN title_mandarin VARCHAR(255);
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_fabric' 
                                 AND column_name = 'weight_mandarin') THEN
                        ALTER TABLE cortex_yen_app_fabric ADD COLUMN weight_mandarin VARCHAR(100);
                    END IF;
                END $$;
            """,
            reverse_sql="-- No reverse operation needed",
        ),
        
        # Use RunSQL to conditionally add model_image_id field if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                 WHERE table_name = 'cortex_yen_app_fabriccolorimage' 
                                 AND column_name = 'model_image_id') THEN
                        ALTER TABLE cortex_yen_app_fabriccolorimage 
                        ADD COLUMN model_image_id INTEGER REFERENCES cortex_yen_app_mediauploads(id);
                    END IF;
                END $$;
            """,
            reverse_sql="-- No reverse operation needed",
        ),
    ]
