# Generated by Django 5.0.4 on 2025-04-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0036_remove_fabriccolorimage_color_contactrequest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabriccolorimage',
            name='color',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fabric',
            name='composition_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='description_mandarin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='finish_mandarin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='title_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='weight_mandarin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabriccolorimage',
            name='model_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_image', to='cortex_yen_app.mediauploads'),
        ),
    ]
