# Generated by Django 5.0.4 on 2025-03-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0036_contactrequest_fabric_item_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_composition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_is_hot_selling',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_composition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_is_hot_selling',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
