# Generated by Django 5.0.4 on 2025-03-26 03:35

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    # Check if the columns exist before trying to add them
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # List of tables and columns to check
            tables_and_columns = [
                ('cortex_yen_app_contactrequest', [
                    ('fabric_category_name', 'VARCHAR(100)'),
                    ('fabric_composition', 'VARCHAR(200)'),
                    ('fabric_description', 'TEXT'),
                    ('fabric_finish', 'VARCHAR(100)'),
                    ('fabric_is_hot_selling', 'BOOLEAN'),
                    ('fabric_weight', 'VARCHAR(50)')
                ]),
                ('cortex_yen_app_orderitem', [
                    ('fabric_category_name', 'VARCHAR(100)'),
                    ('fabric_composition', 'VARCHAR(200)'),
                    ('fabric_description', 'TEXT'),
                    ('fabric_finish', 'VARCHAR(100)'),
                    ('fabric_is_hot_selling', 'BOOLEAN'),
                    ('fabric_weight', 'VARCHAR(50)')
                ])
            ]
            
            for table, columns in tables_and_columns:
                for column, column_type in columns:
                    cursor.execute(f"""
                        SELECT column_name 
                        FROM information_schema.columns 
                        WHERE table_name='{table}' 
                        AND column_name='{column}';
                    """)
                    if not cursor.fetchone():
                        schema_editor.execute(f'ALTER TABLE {table} ADD COLUMN {column} {column_type};')


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0036_contactrequest_fabric_item_code_and_more'),
    ]

    operations = [
        migrations.RunPython(add_fields_if_not_exist, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_composition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_is_hot_selling',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_composition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_is_hot_selling',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
