# Generated by Django 5.0.4 on 2025-03-26 03:35

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    # Check if the columns exist before trying to add them
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # List of tables and columns to check
            tables_and_columns = [
                ('cortex_yen_app_contactrequest', [
                    ('fabric_colors', 'TEXT'),
                    ('fabric_created_at', 'TIMESTAMP WITH TIME ZONE'),
                    ('fabric_images', 'TEXT'),
                    ('fabric_updated_at', 'TIMESTAMP WITH TIME ZONE')
                ]),
                ('cortex_yen_app_orderitem', [
                    ('aux_image1_url', 'VARCHAR(255)'),
                    ('aux_image2_url', 'VARCHAR(255)'),
                    ('aux_image3_url', 'VARCHAR(255)'),
                    ('color_category_color', 'VARCHAR(100)'),
                    ('color_category_name', 'VARCHAR(100)'),
                    ('fabric_created_at', 'TIMESTAMP WITH TIME ZONE'),
                    ('fabric_updated_at', 'TIMESTAMP WITH TIME ZONE'),
                    ('model_image_url', 'VARCHAR(255)'),
                    ('primary_image_url', 'VARCHAR(255)')
                ])
            ]
            
            for table, columns in tables_and_columns:
                for column, column_type in columns:
                    cursor.execute(f"""
                        SELECT column_name 
                        FROM information_schema.columns 
                        WHERE table_name='{table}' 
                        AND column_name='{column}';
                    """)
                    if not cursor.fetchone():
                        schema_editor.execute(f'ALTER TABLE {table} ADD COLUMN {column} {column_type};')


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0037_contactrequest_fabric_category_name_and_more'),
    ]

    operations = [
        migrations.RunPython(add_fields_if_not_exist, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='fabric_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='aux_image1_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='aux_image2_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='aux_image3_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_category_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='model_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='primary_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
