# Generated by Django 5.0.4 on 2025-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0038_add_mandarin_fields_explicitly'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fabriccolorcategory',
            name='display_name_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_mandarin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
