# Generated by Django 5.0.4 on 2025-03-26 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0038_contactrequest_fabric_colors_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fabriccolorimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_category_name',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_colors',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_composition',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_created_at',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_description',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_finish',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_images',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_is_hot_selling',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_item_code',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_title',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_updated_at',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='fabric_weight',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='color_images',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mediauploads',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mediauploads',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='aux_image1_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='aux_image2_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='aux_image3_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_category_color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_category_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_category_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_composition',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_finish',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_is_hot_selling',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_title',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fabric_weight',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='model_image_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='primary_image_url',
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='related_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cortex_yen_app.fabric'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='composition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='item_code',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_item_code', message='Item code must contain only letters and numbers.', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cortex_yen_app.productcategory'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='aux_image1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aux_image1', to='cortex_yen_app.mediauploads'),
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='aux_image2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aux_image2', to='cortex_yen_app.mediauploads'),
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='aux_image3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aux_image3', to='cortex_yen_app.mediauploads'),
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='color_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colors', to='cortex_yen_app.fabriccolorcategory'),
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='cortex_yen_app.fabric'),
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='model_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_image', to='cortex_yen_app.mediauploads'),
        ),
        migrations.AlterField(
            model_name='fabriccolorimage',
            name='primary_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_images', to='cortex_yen_app.mediauploads'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_set', to='cortex_yen_app.fabric'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
