# Generated by Django 5.0.4 on 2025-04-29 16:37

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0039_add_mandarin_fields_to_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_mandarin',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
