# Generated by Django 5.0.4 on 2025-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0039_alter_fabriccolorimage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
