# Generated by Django 5.0.4 on 2025-03-26 03:35

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    # Check if the columns exist before trying to add them
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # List of tables and columns to check
            tables_and_columns = [
                ('cortex_yen_app_contactrequest', [
                    ('name', 'VARCHAR(100)'),
                    ('phone', 'VARCHAR(20)')
                ])
            ]
            
            for table, columns in tables_and_columns:
                for column, column_type in columns:
                    cursor.execute(f"""
                        SELECT column_name 
                        FROM information_schema.columns 
                        WHERE table_name='{table}' 
                        AND column_name='{column}';
                    """)
                    if not cursor.fetchone():
                        schema_editor.execute(f'ALTER TABLE {table} ADD COLUMN {column} {column_type};')


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0039_alter_fabriccolorimage_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(add_fields_if_not_exist, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
