# Generated by Django 5.0.4 on 2025-04-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0040_add_mandarin_fields_to_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='address_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='city_mandarin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='country_mandarin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='county_mandarin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='email_mandarin',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='phone_mandarin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='postal_code_mandarin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_mandarin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_mandarin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
