# Generated by Django 5.0.4 on 2025-04-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0041_add_mandarin_fields_to_contact_details_and_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='email_mandarin',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='phone_mandarin',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='postal_code_mandarin',
        ),
    ]
