# Generated by Django 4.2.4 on 2023-08-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0043_alter_productcategory_options_productcategory_order'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    -- Make sure the color field is removed if it exists
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name = 'cortex_yen_app_fabriccolorimage' 
                             AND column_name = 'color') THEN
                        ALTER TABLE cortex_yen_app_fabriccolorimage DROP COLUMN color;
                    END IF;
                END $$;
            """,
            reverse_sql="-- No reverse operation needed",
        ),
        migrations.RunSQL(
            sql="""
                -- Set order for existing ProductCategory records if any have NULL order
                UPDATE cortex_yen_app_productcategory 
                SET "order" = id - 1
                WHERE "order" IS NULL OR "order" = 0;
            """,
            reverse_sql="-- No reverse operation needed",
        ),
    ]
