# Generated by Django 5.0.4 on 2025-05-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0044_fix_fabriccolorimage_color_field'),
    ]

    operations = [
        # Only include the fabric foreign key changes that we actually need
        migrations.AlterField(
            model_name='cartitem',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cortex_yen_app.fabric'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='related_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cortex_yen_app.fabric'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cortex_yen_app.fabric'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem_set', to='cortex_yen_app.fabric'),
        ),
    ]
