# Generated by Django 5.0.4 on 2024-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0045_fabric_deletion_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='extra_categories',
            field=models.ManyToManyField(blank=True, related_name='extra_fabrics', to='cortex_yen_app.productcategory'),
        ),
    ] 