# Generated by Django 5.0.4 on 2025-07-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0046_fabric_extra_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_mandarin',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category', '-created_at'], name='cortex_yen__categor_f9f632_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-view_count', '-created_at'], name='cortex_yen__view_co_af4690_idx'),
        ),
    ]
