# Generated by Django 5.0.4 on 2025-07-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_yen_app', '0047_alter_blog_options_remove_fabriccolorimage_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
